on:
  push:
    tags:
      - build*

name: build

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set-up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: Rscript install-deps.R

      - name: Download dataset from data-donness.ec.gc.ca
        run: Rscript download.R
      
      - name: Build aggregated CSV files
        run: Rscript format.R

      - name: Add built artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: data/build/CA_NAPS_Daily_*.csv
